env: "kitchen-complete-v0"
n_epochs: 10
seed: 0
feedback_type: [
    "comparative",
    # "attribute",
    # "evaluative",
    # "keypoint",
    # "visual"
]
num_query: 200
len_query: 100
fake_label: false
relabel_human_labels: false 
use_wandb: false